### ISSUE TITLE
Remove EXIF without re-encoding images

### ISSUE THREAD

**Issue by lieut-data** [scottleedavis/mattermost-plugin-noexif#2]
Would it be possible to remove the EXIF without re-encoding the images, potentially changing their size and quality as a result?

https://github.com/dsoprea/go-exif (and the linked https://github.com/dsoprea/go-jpeg-image-structure and https://github.com/dsoprea/go-png-image-structure) purport to allow read-write of EXIF data alone.

**Comment by scottleedavis** [comment]
My first choice was to use go-exif though it's not straight forward on how to write empty exif to the file.  I have a PR to be reviewed and merged to facilitate part of this 
https://github.com/dsoprea/go-exif/pull/21
https://github.com/dsoprea/go-exif/issues/16

Happy to use go-exif when it can write 'empty' exif.  :)

**Comment by scottleedavis** [comment]
Making progress on JPG, though currently only 40% effective.  (direct removal of EXIF bytes).  Progress!  Not yet perfection

**Comment by scottleedavis** [comment]
now seeing 100% effective in tests.  wrote a small wrapper module to remove exif https://github.com/scottleedavis/go-exif-remove
need to do png now.

**Comment by scottleedavis** [comment]
This is complete @lieut-data , however I have created Issue #5 to address a bug found in uploading some types of JPGs.  I will ping you to continue gauntlet review when I have this issue addressed.
