### ISSUE TITLE
Support multiple requests/servers

### ISSUE THREAD

**Issue by lieut-data** [scottleedavis/mattermost-plugin-noexif#3]
The current code keeps track of the modified file ids in a `filesTracked` slice on the plugin instance. This has two shortcomings:
* the `filesTracked` is not guarded by a mutex, so if the plugin receives two requests concurrently, there's a chance the one update might be lost, or worse, that the `filesTracked` slice would be corrupted altogether and panic the plugin
* the `filesTracked` is local to that plugin instance, so knowledge about modified files will be unknown to other plugin instances in an HA deployment.

Solving the former issue is relatively straight forward by wrapping in a mutex, but the latter would require using the key value store's atomic primitives. This would add a certain degree of complexity to the plugin.

Thoughts about just stripping out the notification functionality? Alternatively, it would be neat if we could find a way to attach data to the file upload for later query.

**Comment by scottleedavis** [comment]
The added notification functionality was requested by @aaronrothschild.  Aaron would you be ok with stripping out this functionality to reduce complexity for HA?

Alternatively...  @lieut-data do you mean additional meta data on the file upload hook?

**Comment by aaronrothschild** [comment]
> The added notification functionality was requested by @aaronrothschild. Aaron would you be ok with stripping out this functionality to reduce complexity for HA?

I'm a 2/5 that we should notify the user - I would be OK with reducing complexity.

**Comment by scottleedavis** [comment]
Updated as requested (removed notification functionality)
