### ISSUE TITLE
Errors in some JPG with short Huffman data 

### ISSUE THREAD

**Issue by scottleedavis** [scottleedavis/mattermost-plugin-noexif#5]
Server log
```
ERRO[2019-09-02T15:08:43.979733-07:00] Unable to decode image err=invalid JPEG format: short Huffman data  caller="app/file.go:758"
```
in `app/file.go` the check is done with `image.Decode`.  
```go
decoded, typ, err = image.Decode(t.newReader())
if err != nil {
	mlog.Error(fmt.Sprintf("Unable to decode image err=%v", err))
	return
}
```

It was thought, the associated `jpg.Decode` & `png.Decode` from the `image` package used in [go-exif-remove](https://github.com/scottleedavis/go-exif-remove) would provide the same check, however it does not appear to be catching the short huffman data issue on jpg's.
```go
_, err = jpeg.Decode(bytes.NewReader(filtered))
```
```go
_, err = png.Decode(bytes.NewReader(filtered))
```

Perhaps there is something different between the decode functions between the two or a level of checking that needs to be done in the same way?

**Comment by denieve** [comment]
I try adding 
```go
if _, _, err = image.Decode(bytes.NewReader(filtered)); err != nil {
	errMsg := "ERROR: original image is corrupt " + err.Error()
	p.API.LogInfo(errMsg)
	return nil, errMsg
}	
```
after the `exifremove.Remove` to catch same error before plugin back to server, but get no error.  Something config different server side?

**Comment by scottleedavis** [comment]
line #53 https://golang.org/src/image/jpeg/huffman.go

**Comment by scottleedavis** [comment]
The issue is sporadic.  The same image may parse, and may not under circumstances not clear.  It is definitely server side (plugin parsing seems ok)

**Comment by scottleedavis** [comment]
Aha!  Very strange.  If I add to app/file.go on the server, a small sleep of 100 ms delay before the creation of the io.Reader on the file, it is 100% success rate on remove & upload
```go
func (t uploadFileTask) newReader() io.Reader {
	time.Sleep(time.Millisecond * 100)
	if t.teeInput != nil {
		return io.MultiReader(bytes.NewReader(t.buf.Bytes()), t.teeInput)
	} else {
		return bytes.NewReader(t.buf.Bytes())
	}
}
```

**Comment by scottleedavis** [comment]
Fixed with this [patch](https://gist.github.com/streamer45/8f4b0295ee1dda6798d0d332bc64b257)

Discussion https://community.mattermost.com/core/pl/5p9fjcqk3tdw7brjpfm1f3poza
